# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6213ff29d0199b4846ac4fbe827fbd748e06218185aaba56f25246eb20bf17e4a7033379b42bcdedf338a6dc90e41d45e5a8f20cb8b752d4adffc6fa7dcd447e

test:
  secret_key_base: 62560b7c11bde6b58d0a1e2b3b018015e8bb90070975beeffc9cb20fce26cd084d30b41841838496057ef248e93ff1a8f4c7e10ebe3c57d280622cf6d9d89cb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
